"""GeoLedger Security Package."""

from backend.security.permissions import (
    get_user_permissions,
    user_has_permission,
    ROLE_PERMISSIONS_MAP,
    DOCUMENTS_UPLOAD,
    DOCUMENTS_READ_OWN,
    DOCUMENTS_READ_SCOPED,
    DOCUMENTS_READ_ALL,
    DOCUMENTS_EDIT_EXTRACTION,
    DOCUMENTS_DELETE_OWN,
    DOCUMENTS_DELETE_ALL,
    DOCUMENTS_VERIFY,
    PARCELS_READ_OWN,
    PARCELS_READ_SCOPED,
    PARCELS_READ_ALL,
    PARCELS_EDIT,
    VERIFICATION_CREATE,
    VERIFICATION_READ_OWN,
    VERIFICATION_READ_SCOPED,
    VERIFICATION_READ_ALL,
    VERIFICATION_REVIEW,
    VERIFICATION_CORRECT,
    VERIFICATION_APPROVE,
    VERIFICATION_REJECT,
    VERIFICATION_RETURN,
    VERIFICATION_OVERRIDE,
    GIS_READ_OWN,
    GIS_READ_SCOPED,
    GIS_READ_ALL,
    GIS_EDIT,
    GIS_APPROVE_GEOMETRY,
    USERS_READ,
    USERS_CREATE,
    USERS_UPDATE,
    USERS_DEACTIVATE,
    USERS_ASSIGN_ROLE,
    JURISDICTIONS_MANAGE,
    ROLES_READ,
    ROLES_MANAGE,
    AUDIT_READ_OWN,
    AUDIT_READ_SCOPED,
    AUDIT_READ_ALL,
    AUDIT_EXPORT,
    SYSTEM_CONFIGURE,
)
from backend.security.jurisdiction import (
    get_user_jurisdictions,
    is_resource_in_jurisdiction,
    filter_documents_by_scope,
    filter_parcels_by_scope,
    filter_cases_by_scope,
)
from backend.security.authorization import (
    require_permission,
    authorize_document_access,
    authorize_parcel_access,
    check_verification_conflict,
    validate_workflow_transition,
    log_security_event,
)
from backend.security.field_versioning import (
    record_field_extraction,
    record_officer_correction,
    record_final_verification,
    get_field_audit_lineage,
)
